#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allclean

restore0Dir
runApplication blockMesh
runApplication topoSet
runApplication getCellCentres
python3 get_expData.py
touch case.foam
runApplication speciesBoussinesqPimpleFoam

#runApplication decomposePar
#runApplication mpirun -n 2 speciesBoussinesqPimpleFoam -parallel

## Command to get VTK files for each time step for post processing
#bash getVTK.sh

#------------------------------------------------------------------------------
