#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

cleanTimeDirectories
cleanPostProcessing

rm -rf history
rm -rf processor*
#rm log.*
rm *.csv
#------------------------------------------------------------------------------
