#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allclean

restore0Dir
runApplication blockMesh
touch case.foam
runApplication speciesBoussinesqPimpleFoam

#runApplication decomposePar
#runApplication mpirun -n 2 speciesBoussinesqPimpleFoam -parallel
#------------------------------------------------------------------------------
